In [2]:
import pandas as pd


import numpy as np
import pandas as pd

import seaborn as sns

import matplotlib.pyplot as plt
%matplotlib inline

from datetime import datetime

In [3]:
path = '/data/public/MLA/VCHAMPS-Test/immunization_test.csv'
immunization = pd.read_csv(path).iloc[:,1:]

In [4]:
immunization.head()

,Internalpatientid,Age at immunization,Immunization date,Immunization,Dose quantity,Dose unit,Administered elsewhere,Cvx code,Series doses,State
0,100,52.898575,2014-08-21 10:17:59.0,"PNEUMOCOCCAL, UNSPECIFIED FORMULATION",NaN,NaN,NaN,109.0,Not specified (no value),New York
1,100,52.898575,2014-08-21 10:17:59.0,"FLU,3 YRS (HISTORICAL)",NaN,NaN,NaN,88.0,Not specified (no value),New York
2,100,52.898575,2014-08-21 10:17:59.0,"INFLUENZA, UNSPECIFIED FORMULATION",NaN,NaN,NaN,88.0,Not specified (no value),New York
3,100041,88.331313,2013-08-05 02:16:33.0,TD(ADULT) UNSPECIFIED FORMULATION,NaN,NaN,NaN,139.0,Not specified (no value),Minnesota
4,100041,88.331313,2013-08-05 02:16:33.0,"NOVEL INFLUENZA-H1N1-09, ALL FORMULATIONS",NaN,NaN,NaN,128.0,Not specified (no value),Minnesota

In [5]:
immunization['Immunization'] = immunization['Immunization'].str.lower()
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'influence' if 'flu' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'influence' if 'hib' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'influence' if 'h1n1' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'pneumococcal' if 'pneum' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'pneumococcal' if 'prevnar' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'pneumococcal' if 'pcv' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'tetanus/diptheria' if 'tet' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'tetanus/diptheria' if 'dtap' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'tetanus/diptheria' if 'dt' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'tetanus/diptheria' if 'td' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'tetanus/diptheria' if 'tdap' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'tetanus/diptheria' if 't-dap' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'tetanus/diptheria' if 'diphtheria' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'hepatitis' if 'hep' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'rabies/intramuscular injection' if 'rabi' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'mmr' if 'mumps' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'mmr' if 'mmr' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'mmr' if 'rubella' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'mmr' if 'mmrv' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'mmr' if 'm/r' in str(x) else str(x))

immunization.Immunization=  immunization.Immunization.apply(lambda x: 'meningococcal' if 'mening' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'zoster' if 'zoster' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'zoster' if 'varicella' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'zoster' if 'zostravax' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'hpv' if 'hpv' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'hpv' if 'garda' in str(x) else str(x)) # gardacil & gardasil

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'covid' if 'covid' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'skin test' if 'ppd' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'skin test' if 'skin' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'fever' if 'yellow' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'fever' if 'typhoid' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'zostavax' if 'zostav' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'zostavax' if 'shingles' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'polio vaccine' if 'polio' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'polio vaccine' if 'opv' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'polio vaccine' if 'ipv' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'encephalitis' if 'japanese' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'encephalitis' if 'encephalitis' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'vitamin' if 'vitamin' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'bcg' if 'bcg' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'adenovirus' if 'adenovirus' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'twinrix' if 'twinrix' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'other' if 'unlisted' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'other' if 'nan' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'other' if 'error' in str(x) else str(x))

In [6]:
tmp = pd.DataFrame(immunization['Immunization'].value_counts())
tmp = tmp.reset_index()
tmp.columns = ['Immunization', 'counts']
tmp

                          Immunization  counts
0                            influence  323808
1                         pneumococcal   65747
2                    tetanus/diptheria   48014
3                                covid   24241
4                               zoster   17637
5                            hepatitis    5841
6                                  bcg     347
7                            skin test     336
8                        meningococcal     187
9                             zostavax     105
10                                 mmr      66
11                               fever      57
12      rabies/intramuscular injection      55
13                               other      48
14                             vitamin      31
15           testosterone (historical)      28
16                       polio vaccine      22
17                                 hpv      19
18         gamma globulin (historical)      10
19                        encephalitis       6
20                             twinrix       6
21                             measles       5
22       leuprolide given (historical)       3
23                 vaccinia (smallpox)       2
24                        lyme disease       2
25            depo medrol (historical)       2
26                          adenovirus       2
27                    b12 (historical)       2
28                              plague       1
29                             anthrax       1
30           solu medrol  (historical)       1
31                kenalog (historical)       1
32  rotavirus, unspecified formulation       1

In [7]:
immuns = ['zostavax',
 'pneumococcal',
 'covid',
 'gamma globulin (historical)',
 'bcg',
 'tetanus/diptheria',
 'mmr',
 'influence',
 'zoster',
 'meningococcal',
 'fever',
 'hepatitis',
 'rabies/intramuscular injection',
 'skin test']

In [8]:
immunization_10 = immunization.loc[immunization['Immunization'].isin(immuns)]
immunization_10

,Internalpatientid,Age at immunization,Immunization date,Immunization,Dose quantity,Dose unit,Administered elsewhere,Cvx code,Series doses,State
0,100,52.898575,2014-08-21 10:17:59.0,pneumococcal,NaN,NaN,NaN,109.0,Not specified (no value),New York
1,100,52.898575,2014-08-21 10:17:59.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),New York
2,100,52.898575,2014-08-21 10:17:59.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),New York
3,100041,88.331313,2013-08-05 02:16:33.0,tetanus/diptheria,NaN,NaN,NaN,139.0,Not specified (no value),Minnesota
4,100041,88.331313,2013-08-05 02:16:33.0,influence,NaN,NaN,NaN,128.0,Not specified (no value),Minnesota
...,...,...,...,...,...,...,...,...,...,...
486629,99958,79.600992,2005-09-15 03:54:19.0,influence,NaN,NaN,NaN,16.0,Not specified (no value),New York
486630,99958,79.600992,2005-09-15 03:54:19.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),New York
486631,99979,57.915172,2005-04-04 23:53:11.0,tetanus/diptheria,NaN,NaN,NaN,139.0,Not specified (no value),North Carolina
486632,99997,85.682957,2014-10-28 02:53:46.0,zoster,NaN,NaN,NaN,121.0,Not specified (no value),North Carolina
486633,99997,87.109014,2016-04-01 08:16:07.0,influence,NaN,NaN,NaN,140.0,Not specified (no value),North Carolina

In [9]:
immunization_10 = immunization_10.drop_duplicates(subset = ['Internalpatientid','Immunization'],keep = 'first')
immunization_10 = immunization_10.reset_index(drop = True)
immunization_10

,Internalpatientid,Age at immunization,Immunization date,Immunization,Dose quantity,Dose unit,Administered elsewhere,Cvx code,Series doses,State
0,100,52.898575,2014-08-21 10:17:59.0,pneumococcal,NaN,NaN,NaN,109.0,Not specified (no value),New York
1,100,52.898575,2014-08-21 10:17:59.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),New York
2,100041,88.331313,2013-08-05 02:16:33.0,tetanus/diptheria,NaN,NaN,NaN,139.0,Not specified (no value),Minnesota
3,100041,88.331313,2013-08-05 02:16:33.0,influence,NaN,NaN,NaN,128.0,Not specified (no value),Minnesota
4,100054,73.257160,2020-08-05 11:48:22.0,zoster,NaN,NaN,NaN,187.0,1,Nebraska
...,...,...,...,...,...,...,...,...,...,...
103615,99608,90.895842,2020-04-18 10:19:40.0,hepatitis,NaN,NaN,NaN,43.0,2,Georgia
103616,99655,57.815085,2005-12-14 09:55:43.0,pneumococcal,NaN,NaN,NaN,33.0,Not specified (no value),Pennsylvania
103617,99824,82.764146,2010-05-17 07:05:16.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),Illinois
103618,99906,65.548024,2002-07-10 19:15:44.0,pneumococcal,NaN,NaN,PrIVATE FACILITY,109.0,Not specified (no value),Kentucky
103619,99997,85.682957,2014-10-28 02:53:46.0,zoster,NaN,NaN,NaN,121.0,Not specified (no value),North Carolina

In [10]:
immunization_10['num_immunization'] = immunization_10['Immunization'].groupby(immunization_10['Internalpatientid']).transform('count')
immunization_10 = immunization_10.sort_values(by = 'Internalpatientid')
immunization_10 = immunization_10.reset_index(drop = True)
immunization_10

,Internalpatientid,Age at immunization,Immunization date,Immunization,Dose quantity,Dose unit,Administered elsewhere,Cvx code,Series doses,State,num_immunization
0,6,79.465447,2006-02-24 14:54:17.0,pneumococcal,NaN,NaN,NaN,109.0,Complete,Texas,3
1,6,74.147397,2000-10-29 20:58:06.0,tetanus/diptheria,NaN,NaN,NaN,139.0,Not specified (no value),Texas,3
2,6,75.805057,2002-06-27 17:57:25.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),Texas,3
3,7,70.003145,2016-07-10 03:35:27.0,influence,NaN,NaN,NaN,150.0,Not specified (no value),Nebraska,5
4,7,61.123422,2007-08-21 14:39:23.0,skin test,NaN,NaN,NaN,NaN,Not specified (no value),Nebraska,5
...,...,...,...,...,...,...,...,...,...,...,...
103615,169059,81.316251,2004-07-30 02:09:29.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),Arizona,2
103616,169059,87.304886,2010-07-27 22:27:45.0,pneumococcal,NaN,NaN,NaN,109.0,Not specified (no value),Arizona,2
103617,169065,47.426028,2005-07-18 05:07:17.0,pneumococcal,NaN,NaN,NaN,33.0,Not specified (no value),California,3
103618,169065,49.027339,2007-02-23 11:48:49.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),Arizona,3
103619,169065,40.654422,1998-10-08 04:35:27.0,tetanus/diptheria,NaN,NaN,Tucson VAMC,139.0,Not specified (no value),California,3

In [12]:
# Find the pid that in immunization but not in immunization_10
pid = list(set(immunization['Internalpatientid'].unique()).difference(immunization_10['Internalpatientid'].unique()))
df1 = pd.DataFrame({'Internalpatientid':pid, 'num_immunization':[0]})

In [13]:
columns = ['Internalpatientid','num_immunization']
df = immunization_10[columns]
df = df.append(df1)
df = df.groupby('Internalpatientid').apply(lambda x:x)
df = df.drop_duplicates(keep = 'first').reset_index(drop = True)
df

/tmp/ipykernel_123085/109899019.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df1)
/tmp/ipykernel_123085/109899019.py:4: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df = df.groupby('Internalpatientid').apply(lambda x:x)

       Internalpatientid  num_immunization
0                      6                 3
1                 145205                 0
2                      7                 5
3                     12                 1
4                     17                 3
...                  ...               ...
32779             169024                 1
32780             169037                 4
32781             169045                 4
32782             169059                 2
32783             169065                 3

[32784 rows x 2 columns]

In [14]:
#df.to_csv('/home/daisy/FDA_Dataset/immunization_test_clean.csv')