In [1]:
import pandas as pd


import numpy as np
import pandas as pd

import seaborn as sns

import matplotlib.pyplot as plt
%matplotlib inline

from datetime import datetime

In [2]:
path = '/data/public/MLA/VCHAMPS-Quality/immunization_qual.csv'
immunization = pd.read_csv(path).iloc[:,1:]

In [3]:
immunization['Immunization'] = immunization['Immunization'].str.lower()
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'influence' if 'flu' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'influence' if 'hib' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'influence' if 'h1n1' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'pneumococcal' if 'pneum' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'pneumococcal' if 'prevnar' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'pneumococcal' if 'pcv' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'tetanus/diptheria' if 'tet' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'tetanus/diptheria' if 'dtap' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'tetanus/diptheria' if 'dt' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'tetanus/diptheria' if 'td' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'tetanus/diptheria' if 'tdap' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'tetanus/diptheria' if 't-dap' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'tetanus/diptheria' if 'diphtheria' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'hepatitis' if 'hep' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'rabies/intramuscular injection' if 'rabi' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'mmr' if 'mumps' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'mmr' if 'mmr' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'mmr' if 'rubella' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'mmr' if 'mmrv' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'mmr' if 'm/r' in str(x) else str(x))

immunization.Immunization=  immunization.Immunization.apply(lambda x: 'meningococcal' if 'mening' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'zoster' if 'zoster' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'zoster' if 'varicella' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'zoster' if 'zostravax' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'hpv' if 'hpv' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'hpv' if 'garda' in str(x) else str(x)) # gardacil & gardasil

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'covid' if 'covid' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'skin test' if 'ppd' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'skin test' if 'skin' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'fever' if 'yellow' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'fever' if 'typhoid' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'zostavax' if 'zostav' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'zostavax' if 'shingles' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'polio vaccine' if 'polio' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'polio vaccine' if 'opv' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'polio vaccine' if 'ipv' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'encephalitis' if 'japanese' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'encephalitis' if 'encephalitis' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'vitamin' if 'vitamin' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'bcg' if 'bcg' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'adenovirus' if 'adenovirus' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'twinrix' if 'twinrix' in str(x) else str(x))

immunization.Immunization =  immunization.Immunization.apply(lambda x: 'other' if 'unlisted' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'other' if 'nan' in str(x) else str(x))
immunization.Immunization =  immunization.Immunization.apply(lambda x: 'other' if 'error' in str(x) else str(x))

In [4]:
tmp = pd.DataFrame(immunization['Immunization'].value_counts())
tmp = tmp.reset_index()
tmp.columns = ['Immunization', 'counts']
tmp

                      Immunization  counts
0                        influence    9026
1                     pneumococcal    1850
2                tetanus/diptheria    1363
3                            covid     641
4                           zoster     514
5                        hepatitis     158
6                              bcg      18
7                        skin test       6
8                              mmr       4
9   rabies/intramuscular injection       2
10                        zostavax       1
11                           other       1
12                   meningococcal       1

In [5]:
immuns = ['zostavax',
 'pneumococcal',
 'covid',
 'gamma globulin (historical)',
 'bcg',
 'tetanus/diptheria',
 'mmr',
 'influence',
 'zoster',
 'meningococcal',
 'fever',
 'hepatitis',
 'rabies/intramuscular injection',
 'skin test']

In [6]:
immunization_10 = immunization.loc[immunization['Immunization'].isin(immuns)]
immunization_10

,Internalpatientid,Age at immunization,Immunization date,Immunization,Dose quantity,Dose unit,Administered elsewhere,Cvx code,Series doses,State
0,100229,68.021827,2000-09-25 23:27:52.0,pneumococcal,NaN,NaN,NaN,109.0,Not specified (no value),Arizona
1,100229,68.021827,2000-09-25 23:27:52.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),Arizona
2,100314,64.986914,2011-07-04 17:12:36.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),Missouri
3,100399,77.128884,2001-08-23 14:34:16.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),Minnesota
4,100399,78.234635,2002-10-01 18:13:15.0,tetanus/diptheria,NaN,NaN,NaN,139.0,Not specified (no value),Minnesota
...,...,...,...,...,...,...,...,...,...,...
13580,99143,90.632019,2012-01-15 00:04:27.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),Florida
13581,9947,67.200942,2010-10-16 22:39:38.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),Ohio
13582,9947,67.200942,2010-10-16 22:39:38.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),Ohio
13583,99941,76.400998,2018-12-19 13:33:08.0,influence,NaN,NaN,NaN,141.0,Not specified (no value),Maine
13584,99944,80.397951,2012-12-01 10:49:45.0,pneumococcal,NaN,NaN,NaN,109.0,Not specified (no value),Massachusetts

In [7]:
immunization_10 = immunization_10.drop_duplicates(subset = ['Internalpatientid','Immunization'],keep = 'first')
immunization_10 = immunization_10.reset_index(drop = True)
immunization_10

,Internalpatientid,Age at immunization,Immunization date,Immunization,Dose quantity,Dose unit,Administered elsewhere,Cvx code,Series doses,State
0,100229,68.021827,2000-09-25 23:27:52.0,pneumococcal,NaN,NaN,NaN,109.0,Not specified (no value),Arizona
1,100229,68.021827,2000-09-25 23:27:52.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),Arizona
2,100314,64.986914,2011-07-04 17:12:36.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),Missouri
3,100399,77.128884,2001-08-23 14:34:16.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),Minnesota
4,100399,78.234635,2002-10-01 18:13:15.0,tetanus/diptheria,NaN,NaN,NaN,139.0,Not specified (no value),Minnesota
...,...,...,...,...,...,...,...,...,...,...
2912,99870,75.690357,1997-02-18 19:48:47.0,pneumococcal,NaN,NaN,NaN,109.0,Not specified (no value),South Dakota
2913,99870,75.690357,1997-02-18 19:48:47.0,tetanus/diptheria,NaN,NaN,NaN,139.0,Not specified (no value),South Dakota
2914,99870,86.275133,2007-09-23 13:27:59.0,zoster,NaN,NaN,NaN,121.0,Complete,South Dakota
2915,99137,72.394421,2003-02-26 03:51:41.0,pneumococcal,NaN,NaN,NaN,109.0,Not specified (no value),Texas
2916,99944,80.397951,2012-12-01 10:49:45.0,pneumococcal,NaN,NaN,NaN,109.0,Not specified (no value),Massachusetts

In [8]:
immunization_10['num_immunization'] = immunization_10['Immunization'].groupby(immunization_10['Internalpatientid']).transform('count')
immunization_10 = immunization_10.sort_values(by = 'Internalpatientid')
immunization_10 = immunization_10.reset_index(drop = True)
immunization_10

,Internalpatientid,Age at immunization,Immunization date,Immunization,Dose quantity,Dose unit,Administered elsewhere,Cvx code,Series doses,State,num_immunization
0,67,49.940158,2012-04-06 03:03:52.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),California,5
1,67,51.655053,2013-12-23 22:07:25.0,pneumococcal,NaN,NaN,NaN,133.0,Not specified (no value),California,5
2,67,58.154687,2020-06-25 12:55:06.0,zoster,NaN,NaN,NaN,187.0,2,California,5
3,67,58.154687,2020-06-25 12:55:06.0,tetanus/diptheria,NaN,NaN,NaN,115.0,Not specified (no value),California,5
4,67,57.325619,2019-08-27 12:19:32.0,covid,NaN,NaN,NaN,208.0,1,California,5
...,...,...,...,...,...,...,...,...,...,...,...
2912,168496,98.066514,2022-03-11 07:27:46.0,covid,NaN,NaN,NaN,207.0,2,California,3
2913,168496,93.524107,2017-08-24 01:28:02.0,pneumococcal,NaN,NaN,NaN,133.0,Not specified (no value),California,3
2914,168496,85.451504,2009-07-26 12:35:28.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),California,3
2915,168899,77.553605,2000-05-13 20:13:36.0,pneumococcal,NaN,NaN,NaN,109.0,Not specified (no value),Pennsylvania,2
2916,168899,79.839591,2002-08-27 08:53:34.0,influence,NaN,NaN,NaN,88.0,Not specified (no value),Pennsylvania,2

In [10]:
# Find the pid that in immunization but not in immunization_10
pid = list(set(immunization['Internalpatientid'].unique()).difference(immunization_10['Internalpatientid'].unique()))
pid
#df1 = pd.DataFrame({'Internalpatientid':pid, 'num_immunization':[0]})

[]

In [11]:
columns = ['Internalpatientid','num_immunization']
df = immunization_10[columns]
#df = df.append(df1)
df = df.groupby('Internalpatientid').apply(lambda x:x)
df = df.drop_duplicates(keep = 'first').reset_index(drop = True)
df

/tmp/ipykernel_260238/1311284154.py:4: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df = df.groupby('Internalpatientid').apply(lambda x:x)

     Internalpatientid  num_immunization
0                   67                 5
1                  200                 6
2                  291                 2
3                  330                 4
4                  351                 1
..                 ...               ...
934             167907                 3
935             167917                 4
936             168008                 3
937             168496                 3
938             168899                 2

[939 rows x 2 columns]

In [12]:
df.to_csv('/home/daisy/FDA_Dataset/immunization_quality_admission.csv')