In [1]:
import pandas as pd


import numpy as np
import pandas as pd

import seaborn as sns

import matplotlib.pyplot as plt
%matplotlib inline

from datetime import datetime

In [2]:
# no date
path = '/home/daisy/FDA_Dataset/demographics_static_quality_admission.csv'
demographic_static = pd.read_csv(path).iloc[:,1:]

# no date
path = '/home/daisy/FDA_Dataset/immunization_quality_admission.csv'
immunization = pd.read_csv(path).iloc[:,1:]

path = '/home/daisy/FDA_Dataset/inpatient_medications_ordered_allcause_mortality_quality.csv'
medications_ordered = pd.read_csv(path).iloc[:,1:]

path = '/home/daisy/FDA_Dataset/inpatient_procedures_clean_allcause_mortality_quality.csv'
procedures = pd.read_csv(path).iloc[:,1:]

In [3]:
# path = '/home/hassan/lily/MLA/FDA/outpatient_mortality.csv'
# outpatient_visits = pd.read_csv(path).iloc[:,1:]

path ='/home/vivi/FDA_datasets/inpatient_specialty_allcause_mortality_quality.csv'
inpatient_specialty = pd.read_csv(path).iloc[:,1:]

# no date
path ='/home/vivi/FDA_datasets/demographics_event_quality_admission.csv'
demographics_event = pd.read_csv(path).iloc[:,1:]
demographics_event = demographics_event.drop(columns = ['Age at update','State'])

# no date
path = '/home/vivi/FDA_datasets/outpatient_state_quality_admission.csv'
outpatient_state = pd.read_csv(path).iloc[:,1:]

path = '/home/vivi/FDA_datasets/inpatient_measurements_bp_allcause_mortality_quality.csv'
measurements_bp = pd.read_csv(path).iloc[:,1:]

In [4]:
path = '/home/hassan/lily/MLA/FDA/inpatient_simple_quality.csv'
inpatient = pd.read_csv(path).iloc[:,1:]

path = '/home/hassan/lily/MLA/FDA/lab_results_allcause_mortality_quality.csv'
lab_results = pd.read_csv(path).iloc[:,1:]
lab_results = lab_results.rename(columns = {'count':'lab_count', 'freq':'lab_freq', 
                              'age_mean':'lab_age_mean', 'age_std':'lab_age_std'})

In [12]:
df1 = inpatient.merge(procedures, how = 'left', on = 'Internalpatientid')
df2 = df1.merge(demographic_static, how = 'left', on = 'Internalpatientid')
df3 = df2.merge(immunization, how = 'left', on = 'Internalpatientid')
df4 = df3.merge(medications_ordered, how = 'left', on = 'Internalpatientid')

df5 = df4.merge(inpatient_specialty, how = 'left', on = 'Internalpatientid')
df6 = df5.merge(demographics_event, how = 'left', on = 'Internalpatientid')
df7 = df6.merge(outpatient_state, how = 'left', on = 'Internalpatientid')
df8 = df7.merge(measurements_bp, how = 'left', on = 'Internalpatientid')

df = df8.merge(lab_results, how = 'left', on = 'Internalpatientid')

In [13]:
df

,Internalpatientid,num_stays,stay_length,num_unique_units,num_transfers,num_cvd_admission,CVD,unique_admitting_specialty,unique_discharging_specialty,DOMICILIARY,...,Age 100-120 healthy,Age 20-40 hypertension,Age 40-60 hypertension,Age 60-80 hypertension,Age 80-100 hypertension,Age 100-120 hypertension,lab_count,lab_freq,lab_age_mean,lab_age_std
0,67,1,0.18,1,0,0,0,1,1,0,...,0.0,0.0,78.0,0.0,0.0,0.0,41.0,3.73,52.601590,2.963822
1,200,4,17.90,2,0,0,0,4,3,0,...,0.0,0.0,0.0,68.0,53.0,0.0,255.0,11.59,78.351188,4.920841
2,291,7,79.68,2,0,3,1,3,2,0,...,0.0,0.0,0.0,0.0,57.0,0.0,291.0,72.75,82.348391,1.191165
3,330,3,17.38,1,0,1,1,2,2,0,...,0.0,0.0,4.0,26.0,0.0,0.0,224.0,9.74,68.476453,4.950045
4,351,3,22.14,1,0,3,1,2,2,0,...,0.0,0.0,0.0,0.0,117.0,0.0,102.0,51.00,85.088940,0.453117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627,166881,1,2.52,1,0,1,1,1,1,0,...,0.0,0.0,0.0,42.0,0.0,0.0,60.0,20.00,75.409397,0.758989
628,167102,3,10.25,1,0,0,0,3,1,0,...,0.0,0.0,0.0,137.0,13.0,0.0,398.0,19.90,70.730963,5.095427
629,167404,1,11.63,1,0,1,1,1,1,0,...,0.0,0.0,0.0,17.0,0.0,0.0,47.0,23.50,77.886036,0.237053
630,167917,4,10.50,1,0,1,1,4,2,0,...,0.0,0.0,117.0,0.0,0.0,0.0,60.0,6.00,45.146645,2.375770
631,168008,9,25.07,3,0,0,0,4,4,0,...,0.0,0.0,0.0,207.0,0.0,0.0,167.0,33.40,72.049028,1.506570

In [14]:
df.columns

Index(['Internalpatientid', 'num_stays', 'stay_length', 'num_unique_units',
       'num_transfers', 'num_cvd_admission', 'CVD',
       'unique_admitting_specialty', 'unique_discharging_specialty',
       'DOMICILIARY', 'MEDICINE', 'NHCU', 'NON-COUNT', 'OTHERS', 'PSYCHIATRY',
       'SURGERY', 'Age 20-40', 'Age 40-60', 'Age 60-80', 'Age 80-100',
       'Age 100-120', 'age_mean', 'age_std', 'age_min', 'age_max', 'stay_min',
       'stay_max', 'stay_mean', 'stay_std', 'freq', 'Medical', 'Mental',
       'Others_Specialty', 'Rehab', 'Gerontology', 'CVD_readmission',
       'next_readmission_time', 'Discharge date',
       'readmission within 300 days', 'total_procedure', 'num_surgery_pro',
       'Ethnicity', 'Gender', 'Races', 'Veteran flag', 'Ethnicity_0',
       'Ethnicity_1', 'Ethnicity_2', 'Races_0', 'Races_1', 'Races_2',
       'Races_3', 'num_immunization', 'Num med per admission mean',
       'Num med per admission min', 'Num med per admission max',
       'Total medications', 'mean age at specailty', 'specialty count',
       'period mean', 'period std', 'specialty medical count',
       'specialty support count', 'Event date', 'Marital status',
       'Ruca category', 'Marital status encoded', 'Ruca category encoded',
       'State', 'last_visit_date', 'Age 20-40 hypotension',
       'Age 40-60 hypotension', 'Age 60-80 hypotension',
       'Age 80-100 hypotension', 'Age 100-120 hypotension',
       'Age 20-40 healthy', 'Age 40-60 healthy', 'Age 60-80 healthy',
       'Age 80-100 healthy', 'Age 100-120 healthy', 'Age 20-40 hypertension',
       'Age 40-60 hypertension', 'Age 60-80 hypertension',
       'Age 80-100 hypertension', 'Age 100-120 hypertension', 'lab_count',
       'lab_freq', 'lab_age_mean', 'lab_age_std'],
      dtype='object')

In [15]:
df1 = df.drop(columns = ['Event date','Marital status', 'Marital status encoded','next_readmission_time',
                        'State','Ruca category','Veteran flag', 'last_visit_date', 'Discharge date'])
len(df1.columns)

80

In [16]:
df1.to_csv('/home/daisy/FDA_Dataset/final_allcause_mortality_quality_1.csv')

## Inner join

In [17]:
df1 = inpatient.merge(procedures, how = 'inner', on = 'Internalpatientid')
df2 = df1.merge(demographic_static, how = 'inner', on = 'Internalpatientid')
df3 = df2.merge(immunization, how = 'inner', on = 'Internalpatientid')
df4 = df3.merge(medications_ordered, how = 'inner', on = 'Internalpatientid')

df5 = df4.merge(inpatient_specialty, how = 'inner', on = 'Internalpatientid')
df6 = df5.merge(demographics_event, how = 'inner', on = 'Internalpatientid')
df7 = df6.merge(outpatient_state, how = 'inner', on = 'Internalpatientid')
df8 = df7.merge(measurements_bp, how = 'inner', on = 'Internalpatientid')

df_2 = df8.merge(lab_results, how = 'inner', on = 'Internalpatientid')
df_2

,Internalpatientid,num_stays,stay_length,num_unique_units,num_transfers,num_cvd_admission,CVD,unique_admitting_specialty,unique_discharging_specialty,DOMICILIARY,...,Age 100-120 healthy,Age 20-40 hypertension,Age 40-60 hypertension,Age 60-80 hypertension,Age 80-100 hypertension,Age 100-120 hypertension,lab_count,lab_freq,lab_age_mean,lab_age_std
0,200,4,17.90,2,0,0,0,4,3,0,...,0.0,0.0,0.0,68.0,53.0,0.0,255,11.59,78.351188,4.920841
1,291,7,79.68,2,0,3,1,3,2,0,...,0.0,0.0,0.0,0.0,57.0,0.0,291,72.75,82.348391,1.191165
2,330,3,17.38,1,0,1,1,2,2,0,...,0.0,0.0,4.0,26.0,0.0,0.0,224,9.74,68.476453,4.950045
3,351,3,22.14,1,0,3,1,2,2,0,...,0.0,0.0,0.0,0.0,117.0,0.0,102,51.00,85.088940,0.453117
4,960,1,22.71,1,0,0,0,1,1,0,...,0.0,0.0,13.0,0.0,0.0,0.0,71,10.14,58.467814,1.602777
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,166229,21,107.09,4,1,0,0,12,8,0,...,0.0,107.0,160.0,0.0,0.0,0.0,205,41.00,39.648540,1.576924
438,166881,1,2.52,1,0,1,1,1,1,0,...,0.0,0.0,0.0,42.0,0.0,0.0,60,20.00,75.409397,0.758989
439,167102,3,10.25,1,0,0,0,3,1,0,...,0.0,0.0,0.0,137.0,13.0,0.0,398,19.90,70.730963,5.095427
440,167917,4,10.50,1,0,1,1,4,2,0,...,0.0,0.0,117.0,0.0,0.0,0.0,60,6.00,45.146645,2.375770
441,168008,9,25.07,3,0,0,0,4,4,0,...,0.0,0.0,0.0,207.0,0.0,0.0,167,33.40,72.049028,1.506570

In [18]:
df_2_all = df_2.drop(columns = ['Event date','Marital status', 'Marital status encoded','next_readmission_time',
                        'State','Ruca category','Veteran flag', 'last_visit_date', 'Discharge date'])

In [19]:
len(df_2_all.columns)

80

In [20]:
df_2_all.to_csv('/home/daisy/FDA_Dataset/final_allcause_mortality_quality_2.csv')

In [21]:
inpatient_pid = set(inpatient['Internalpatientid'])
medications_pid = set(medications_ordered['Internalpatientid'])
immunization_pid = set(immunization['Internalpatientid'])
procedures_pid = set(procedures['Internalpatientid'])
demographic_static_pid = set(demographic_static['Internalpatientid'])
inpatient_specialty_pid = set(inpatient_specialty['Internalpatientid'])
demographics_event_pid = set(demographics_event['Internalpatientid'])
outpatient_state_pid = set(outpatient_state['Internalpatientid'])
measurements_bp_pid =set(measurements_bp['Internalpatientid'])
lab_results_pid = set(lab_results['Internalpatientid'])

In [22]:
data_pid = [['inpatient_pid',len(list(inpatient_pid)),len(set.intersection(set(inpatient_pid) & set(inpatient_pid)))],
            ['medications_pid',len(list(medications_pid)),len(set.intersection(set(inpatient_pid) & set(medications_pid)))],
            ['immunization_pid',len(list(immunization_pid)),len(set.intersection(set(inpatient_pid) & set(immunization_pid)))],
            ['procedures_pid',len(list(procedures_pid)),len(set.intersection(set(inpatient_pid) & set(procedures_pid)))],
            ['demographic_static_pid',len(list(demographic_static_pid)),len(set.intersection(set(inpatient_pid) & set(demographic_static_pid)))],
            ['inpatient_specialty_pid',len(list(inpatient_specialty_pid)),len(set.intersection(set(inpatient_pid) & set(inpatient_specialty_pid)))],
            ['demographics_event_pid',len(list(demographics_event_pid)),len(set.intersection(set(inpatient_pid) & set(demographics_event_pid)))],
            ['outpatient_state_pid',len(list(outpatient_state_pid)),len(set.intersection(set(inpatient_pid) & set(outpatient_state_pid)))],
            ['measurements_bp_pid',len(list(measurements_bp_pid)),len(set.intersection(set(inpatient_pid) & set(measurements_bp_pid)))],
            ['lab_results_pid',len(list(lab_results_pid)),len(set.intersection(set(inpatient_pid) & set(lab_results_pid)))]]
df_pid = pd.DataFrame(data_pid, columns = ['table name', 'number of unique pid','intersection pid'])
df_pid['percentage'] = df_pid['intersection pid'] / df_pid['number of unique pid'][0] 
df_pid

                table name  number of unique pid  intersection pid  percentage
0            inpatient_pid                   632               632    1.000000
1          medications_pid                   451               451    0.713608
2         immunization_pid                   939               603    0.954114
3           procedures_pid                  1000               632    1.000000
4   demographic_static_pid                   998               632    1.000000
5  inpatient_specialty_pid                   631               631    0.998418
6   demographics_event_pid                   632               632    1.000000
7     outpatient_state_pid                   632               632    1.000000
8      measurements_bp_pid                  1000               632    1.000000
9          lab_results_pid                   983               631    0.998418