In [1]:
import pandas as pd


import numpy as np
import pandas as pd

import seaborn as sns

import matplotlib.pyplot as plt
%matplotlib inline

from datetime import datetime

In [2]:
# no date
path = '/home/daisy/FDA_Dataset/demographics_static_clean.csv'
demographic_static = pd.read_csv(path).iloc[:,1:]

# no date
path = '/home/daisy/FDA_Dataset/immunization_clean.csv'
immunization = pd.read_csv(path).iloc[:,1:]

path = '/home/daisy/FDA_Dataset/inpatient_medications_ordered_cvd_mortality.csv'
medications_ordered = pd.read_csv(path).iloc[:,1:]

path = '/home/daisy/FDA_Dataset/inpatient_procedures_clean_cvd_mortality.csv'
procedures = pd.read_csv(path).iloc[:,1:]

In [3]:
path = '/home/hassan/lily/MLA/FDA/outpatient_mortality.csv'
outpatient_visits = pd.read_csv(path).iloc[:,1:]

# no date
path ='/home/vivi/FDA_datasets/inpatient_specialty_preprocessed.csv'
inpatient_specialty = pd.read_csv(path).iloc[:,1:]

# no date
path ='/home/vivi/FDA_datasets/demographics_event_preprocessed.csv'
demographics_event = pd.read_csv(path).iloc[:,1:]
demographics_event = demographics_event.drop(columns = ['Age at update','State'])

# no date
path = '/home/vivi/FDA_datasets/outpatient_state.csv'
outpatient_state = pd.read_csv(path).iloc[:,1:]

path = '/home/vivi/FDA_datasets/measurements_bp_cvd_mortality.csv'
measurements_bp = pd.read_csv(path).iloc[:,1:]

In [4]:
path = '/home/hassan/lily/MLA/FDA/inpatient_cvd_mortality.csv'
inpatient = pd.read_csv(path).iloc[:,1:]

path = '/home/hassan/lily/MLA/FDA/lab_results_features.csv'
lab_results = pd.read_csv(path).iloc[:,1:]
lab_results = lab_results.rename(columns = {'count':'lab_count', 'freq':'lab_freq', 
                              'age_mean':'lab_age_mean', 'age_std':'lab_age_std'})

In [5]:
df1 = inpatient.merge(procedures, how = 'left', on = 'Internalpatientid')
df2 = df1.merge(demographic_static, how = 'left', on = 'Internalpatientid')
df3 = df2.merge(immunization, how = 'left', on = 'Internalpatientid')
df4 = df3.merge(medications_ordered, how = 'left', on = 'Internalpatientid')

df5 = df4.merge(inpatient_specialty, how = 'left', on = 'Internalpatientid')
df6 = df5.merge(demographics_event, how = 'left', on = 'Internalpatientid')
df7 = df6.merge(outpatient_state, how = 'left', on = 'Internalpatientid')
df8 = df7.merge(measurements_bp, how = 'left', on = 'Internalpatientid')

df = df8.merge(lab_results, how = 'left', on = 'Internalpatientid')

In [11]:
df

,Internalpatientid,num_stays,stay_length,num_unique_units,num_transfers,num_cvd_admission,AO,CVD,unique_admitting_specialty,unique_discharging_specialty,...,"(0,50]_systolic","(50,60]_systolic","(60,80]_systolic","(80,90]_systolic","(90,100]_systolic","(100,300]_systolic",lab_count,lab_freq,lab_age_mean,lab_age_std
0,3,2,407.50,2,0,1,0,1,2,2,...,0.0,0.0,1.0,0.0,15.0,342.0,1028.0,205.60,80.993657,1.235837
1,4,1,7.15,1,0,1,0,1,1,1,...,0.0,0.0,4.0,4.0,9.0,69.0,98.0,7.00,81.888853,3.082417
2,5,2,8.45,2,0,1,0,1,2,1,...,0.0,0.0,0.0,2.0,1.0,42.0,70.0,23.33,75.972407,0.724535
3,10,1,0.33,1,0,0,1,0,1,1,...,0.0,0.0,0.0,0.0,4.0,25.0,39.0,4.88,66.448542,2.200265
4,15,4,127.10,3,0,3,1,1,4,3,...,0.0,0.0,2.0,10.0,46.0,173.0,74.0,3.52,82.903898,4.043535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61003,169053,12,135.47,3,0,3,0,1,6,6,...,0.0,1.0,1.0,9.0,53.0,459.0,456.0,57.00,79.607835,1.907363
61004,169055,1,6.47,1,0,1,0,1,1,1,...,0.0,0.0,0.0,0.0,1.0,58.0,177.0,14.75,64.458474,3.397283
61005,169060,8,45.38,2,0,6,0,1,5,2,...,0.0,0.0,0.0,4.0,22.0,190.0,399.0,26.60,63.895637,6.083409
61006,169062,12,178.63,4,1,0,1,0,7,5,...,0.0,0.0,0.0,10.0,20.0,158.0,96.0,24.00,72.572363,1.481540
61007,169064,1,7.18,1,0,0,0,0,1,1,...,0.0,0.0,1.0,5.0,11.0,143.0,44.0,2.93,81.663940,3.768916

In [6]:
df.columns

Index(['Internalpatientid', 'num_stays', 'stay_length', 'num_unique_units',
       'num_transfers', 'num_cvd_admission', 'AO', 'CVD',
       'unique_admitting_specialty', 'unique_discharging_specialty',
       'DOMICILIARY', 'MEDICINE', 'NHCU', 'NON-COUNT', 'OTHERS', 'PSYCHIATRY',
       'SURGERY', 'Age 20-40', 'Age 40-60', 'Age 60-80', 'Age 80-100',
       'Age 100-120', 'age_mean', 'age_std', 'age_min', 'age_max', 'stay_min',
       'stay_max', 'stay_mean', 'stay_std', 'freq', 'Medical', 'Mental',
       'Others_Specialty', 'Rehab', 'Gerontology', 'died_by_cvd',
       'Age at death', 'total_procedure', 'num_surgery_pro', 'Ethnicity',
       'Gender', 'Races', 'Veteran flag', 'Ethnicity_0', 'Ethnicity_1',
       'Ethnicity_2', 'Races_0', 'Races_1', 'Races_2', 'Races_3',
       'num_immunization', 'Num med per admission mean',
       'Num med per admission min', 'Num med per admission max',
       'Total medications', 'mean age at specailty', 'specialty count',
       'period mean', 'period std', 'specialty medical count',
       'specialty support count', 'Event date', 'Marital status',
       'Ruca category', 'Marital status encoded', 'Ruca category encoded',
       'State', 'mean age at measurement bp', 'diastolic mean',
       'diastolic std', '(0, 60]', '(60, 80]', '(80, 200]', 'systolic mean',
       'systolic std', '(0,50]_systolic', '(50,60]_systolic',
       '(60,80]_systolic', '(80,90]_systolic', '(90,100]_systolic',
       '(100,300]_systolic', 'lab_count', 'lab_freq', 'lab_age_mean',
       'lab_age_std'],
      dtype='object')

In [8]:
df1 = df.drop(columns = ['Event date','Marital status', 'Marital status encoded',
                        'State','Ruca category','Veteran flag'])
len(df1.columns)

80

In [9]:
df1.to_csv('/home/daisy/FDA_Dataset/final_cvd_mortality_train_1.csv')

## Inner join

In [10]:
df1 = inpatient.merge(procedures, how = 'inner', on = 'Internalpatientid')
df2 = df1.merge(demographic_static, how = 'inner', on = 'Internalpatientid')
df3 = df2.merge(immunization, how = 'inner', on = 'Internalpatientid')
df4 = df3.merge(medications_ordered, how = 'inner', on = 'Internalpatientid')

df5 = df4.merge(inpatient_specialty, how = 'inner', on = 'Internalpatientid')
df6 = df5.merge(demographics_event, how = 'inner', on = 'Internalpatientid')
df7 = df6.merge(outpatient_state, how = 'inner', on = 'Internalpatientid')
df8 = df7.merge(measurements_bp, how = 'inner', on = 'Internalpatientid')

df_2 = df8.merge(lab_results, how = 'inner', on = 'Internalpatientid')
df_2

,Internalpatientid,num_stays,stay_length,num_unique_units,num_transfers,num_cvd_admission,AO,CVD,unique_admitting_specialty,unique_discharging_specialty,...,"(0,50]_systolic","(50,60]_systolic","(60,80]_systolic","(80,90]_systolic","(90,100]_systolic","(100,300]_systolic",lab_count,lab_freq,lab_age_mean,lab_age_std
0,5,2,8.45,2,0,1,0,1,2,1,...,0,0,0,2,1,42,70,23.33,75.972407,0.724535
1,16,11,65.96,2,1,2,0,1,7,2,...,0,0,0,18,66,223,318,24.46,76.443048,1.955840
2,19,8,39.44,3,1,3,0,1,5,6,...,0,0,1,14,16,223,377,22.18,65.008809,4.582627
3,23,9,42.36,3,0,5,0,1,8,4,...,0,0,4,12,45,193,387,32.25,83.592242,3.839411
4,27,2,40.70,2,0,0,0,0,1,1,...,0,0,0,0,2,129,84,8.40,74.353328,3.267350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44084,169050,3,8.30,1,0,0,0,0,3,1,...,0,0,0,0,2,244,205,20.50,58.185697,2.710514
44085,169051,2,6.58,1,0,1,0,1,1,1,...,0,0,0,1,4,147,53,5.89,47.676116,2.252315
44086,169053,12,135.47,3,0,3,0,1,6,6,...,0,1,1,9,53,459,456,57.00,79.607835,1.907363
44087,169062,12,178.63,4,1,0,1,0,7,5,...,0,0,0,10,20,158,96,24.00,72.572363,1.481540
44088,169064,1,7.18,1,0,0,0,0,1,1,...,0,0,1,5,11,143,44,2.93,81.663940,3.768916

In [12]:
df_2_all = df_2.drop(columns = ['Event date','Marital status', 'Marital status encoded',
                        'State','Ruca category','Veteran flag'])

In [13]:
df_2_all.to_csv('/home/daisy/FDA_Dataset/final_cvd_mortality_train_2.csv')