In [1]:
import pandas as pd


import numpy as np
import pandas as pd

import seaborn as sns

import matplotlib.pyplot as plt
%matplotlib inline

from datetime import datetime

In [2]:
# no date
path = '/home/daisy/FDA_Dataset/demographics_static_test_clean.csv'
demographic_static = pd.read_csv(path).iloc[:,1:]

# no date
path = '/home/daisy/FDA_Dataset/immunization_test_clean.csv'
immunization = pd.read_csv(path).iloc[:,1:]

path = '/home/daisy/FDA_Dataset/inpatient_medications_ordered_cvd_mortality_test.csv'
medications_ordered = pd.read_csv(path).iloc[:,1:]

path = '/home/daisy/FDA_Dataset/inpatient_procedures_clean_cvd_mortality_test.csv'
procedures = pd.read_csv(path).iloc[:,1:]

path = '/home/daisy/FDA_Dataset/measurements_cvd_mortality_test.csv'
measurements = pd.read_csv(path).iloc[:,1:]

In [4]:

# no date
path ='/home/vivi/FDA_datasets/inpatient_specialty_cvd_mortality_preprocessed_test.csv'
inpatient_specialty = pd.read_csv(path).iloc[:,1:]

# no date
path ='/home/vivi/FDA_datasets/demographics_event_test.csv'
demographics_event = pd.read_csv(path).iloc[:,1:]
demographics_event = demographics_event.drop(columns = ['Age at update','State'])

# no date
path = '/home/vivi/FDA_datasets/outpatient_state_test.csv'
outpatient_state = pd.read_csv(path).iloc[:,1:]

path = '/home/vivi/FDA_datasets/measurements_bp_cvd_mortality_test.csv'
measurements_bp = pd.read_csv(path).iloc[:,1:]

In [5]:
path = '/home/hassan/lily/MLA/FDA/inpatient_cvd_mortality_test.csv'
inpatient = pd.read_csv(path).iloc[:,1:]

path = '/home/hassan/lily/MLA/FDA/lab_results_features_test.csv'
lab_results = pd.read_csv(path).iloc[:,1:]
lab_results = lab_results.rename(columns = {'count':'lab_count', 'freq':'lab_freq', 
                              'age_mean':'lab_age_mean', 'age_std':'lab_age_std'})

In [6]:
df1 = inpatient.merge(procedures, how = 'left', on = 'Internalpatientid')
df2 = df1.merge(demographic_static, how = 'left', on = 'Internalpatientid')
df3 = df2.merge(immunization, how = 'left', on = 'Internalpatientid')
df4 = df3.merge(medications_ordered, how = 'left', on = 'Internalpatientid')

df5 = df4.merge(inpatient_specialty, how = 'left', on = 'Internalpatientid')
df6 = df5.merge(demographics_event, how = 'left', on = 'Internalpatientid')
df7 = df6.merge(outpatient_state, how = 'left', on = 'Internalpatientid')
df8 = df7.merge(measurements_bp, how = 'left', on = 'Internalpatientid')

df9 = df8.merge(lab_results, how = 'left', on = 'Internalpatientid')
df = df9.merge(measurements, how = 'left', on = 'Internalpatientid')

In [7]:
df

,Internalpatientid,num_stays,stay_length,num_cvd_admission,CVD,Age 20-40,Age 40-60,Age 60-80,Age 80-100,Age 100-120,...,lab_count,lab_freq,lab_age_mean,lab_age_std,Height,Weight,Pulse oximetry min,Pulse oximetry max,Pulse oximetry mean,Pulse oximetry std
0,9,5,25.29,0,0,0,5,0,0,0,...,NaN,NaN,NaN,NaN,65.111111,245.541256,NaN,NaN,NaN,NaN
1,12,6,24.37,5,1,0,0,6,0,0,...,77.0,15.40,71.968368,1.352795,73.830592,173.395117,90.0,101.0,95.800000,3.938415
2,17,13,56.22,5,1,0,0,2,11,0,...,29.0,7.25,81.066231,0.984481,67.763677,172.964936,74.0,105.0,97.523810,6.217870
3,22,5,13.76,0,0,0,1,4,0,0,...,NaN,NaN,NaN,NaN,72.511143,198.266426,86.0,104.0,96.071429,4.999451
4,31,4,59.75,0,0,0,4,0,0,0,...,NaN,NaN,NaN,NaN,67.531250,215.716796,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16690,168995,25,7.90,0,0,0,0,25,0,0,...,35.0,2.06,68.584460,5.570076,69.223547,223.695468,83.0,99.0,92.727273,4.084603
16691,169011,4,3108.65,0,0,0,0,4,0,0,...,21.0,1.24,65.193106,4.343717,72.750000,240.797337,NaN,NaN,NaN,NaN
16692,169037,8,67.38,0,0,0,0,1,7,0,...,20.0,1.33,81.119180,4.266003,65.400000,170.826176,90.0,103.0,96.860000,3.670122
16693,169059,1,8.91,0,0,0,0,1,0,0,...,25.0,2.27,84.353464,3.635745,60.948718,168.921613,NaN,NaN,NaN,NaN
16694,169065,16,122.83,0,0,2,14,0,0,0,...,54.0,3.86,49.633672,4.792535,71.947368,158.746101,86.0,104.0,94.674419,3.424623

In [8]:
df.columns

Index(['Internalpatientid', 'num_stays', 'stay_length', 'num_cvd_admission',
       'CVD', 'Age 20-40', 'Age 40-60', 'Age 60-80', 'Age 80-100',
       'Age 100-120', 'age_mean', 'age_std', 'age_min', 'age_max', 'stay_min',
       'stay_max', 'stay_mean', 'stay_std', 'freq', 'died_by_cvd',
       'Age at death_x', 'Death date', 'num_unique_units', 'num_transfers',
       'unique_admitting_specialty', 'unique_discharging_specialty',
       'DOMICILIARY', 'MEDICINE', 'NHCU', 'NON-COUNT', 'OTHERS', 'PSYCHIATRY',
       'SURGERY', 'Medical', 'Mental', 'Others_Specialty', 'Rehab',
       'Gerontology', 'total_procedure', 'num_surgery_pro', 'Ethnicity',
       'Gender', 'Races', 'Veteran flag', 'Ethnicity_0', 'Ethnicity_1',
       'Ethnicity_2', 'Races_0', 'Races_1', 'Races_2', 'Races_3',
       'num_immunization', 'Num med per admission mean',
       'Num med per admission min', 'Num med per admission max',
       'Total medications', 'mean age at specailty', 'period mean',
       'period std', 'specialty medical count', 'specialty support count',
       'specialty count', 'Event date', 'Marital status', 'Ruca category',
       'Marital status encoded', 'Ruca category encoded', 'State',
       'Age 20-40 hypotension', 'Age 40-60 hypotension',
       'Age 60-80 hypotension', 'Age 80-100 hypotension',
       'Age 100-120 hypotension', 'Age 20-40 healthy', 'Age 40-60 healthy',
       'Age 60-80 healthy', 'Age 80-100 healthy', 'Age 100-120 healthy',
       'Age 20-40 hypertension', 'Age 40-60 hypertension',
       'Age 60-80 hypertension', 'Age 80-100 hypertension',
       'Age 100-120 hypertension', 'lab_count', 'lab_freq', 'lab_age_mean',
       'lab_age_std', 'Height', 'Weight', 'Pulse oximetry min',
       'Pulse oximetry max', 'Pulse oximetry mean', 'Pulse oximetry std'],
      dtype='object')

In [9]:
df1_all = df.drop(columns = ['Age at death_x','Event date','Marital status', 'Marital status encoded',
                        'State','Ruca category','Veteran flag','Death date'])
len(df1_all.columns)

85

In [10]:
df1_all.to_csv('/home/daisy/FDA_Dataset/final_cvd_mortality_test_1.csv')

## Inner join

In [11]:
df1 = inpatient.merge(procedures, how = 'inner', on = 'Internalpatientid')
df2 = df1.merge(demographic_static, how = 'inner', on = 'Internalpatientid')
df3 = df2.merge(immunization, how = 'inner', on = 'Internalpatientid')
df4 = df3.merge(medications_ordered, how = 'inner', on = 'Internalpatientid')

df5 = df4.merge(inpatient_specialty, how = 'inner', on = 'Internalpatientid')
df6 = df5.merge(demographics_event, how = 'inner', on = 'Internalpatientid')
df7 = df6.merge(outpatient_state, how = 'inner', on = 'Internalpatientid')
df8 = df7.merge(measurements_bp, how = 'inner', on = 'Internalpatientid')

df9 = df8.merge(lab_results, how = 'inner', on = 'Internalpatientid')
df_2 = df9.merge(measurements, how = 'inner', on = 'Internalpatientid')

In [12]:
df_2_all = df_2.drop(columns = ['Age at death_x','Event date','Marital status', 'Marital status encoded',
                        'State','Ruca category','Veteran flag','Death date'])

In [13]:
df_2_all.to_csv('/home/daisy/FDA_Dataset/final_cvd_mortality_test_2.csv')

In [14]:
inpatient_pid = set(inpatient['Internalpatientid'])
medications_pid = set(medications_ordered['Internalpatientid'])
immunization_pid = set(immunization['Internalpatientid'])
procedures_pid = set(procedures['Internalpatientid'])
demographic_static_pid = set(demographic_static['Internalpatientid'])
inpatient_specialty_pid = set(inpatient_specialty['Internalpatientid'])
demographics_event_pid = set(demographics_event['Internalpatientid'])
outpatient_state_pid = set(outpatient_state['Internalpatientid'])
measurements_bp_pid =set(measurements_bp['Internalpatientid'])
lab_results_pid = set(lab_results['Internalpatientid'])
measurements_pid = set(measurements['Internalpatientid'])

In [15]:
data_pid = [['inpatient_pid',len(list(inpatient_pid)),len(set.intersection(set(inpatient_pid) & set(inpatient_pid)))],
            ['medications_pid',len(list(medications_pid)),len(set.intersection(set(inpatient_pid) & set(medications_pid)))],
            ['immunization_pid',len(list(immunization_pid)),len(set.intersection(set(inpatient_pid) & set(immunization_pid)))],
            ['procedures_pid',len(list(procedures_pid)),len(set.intersection(set(inpatient_pid) & set(procedures_pid)))],
            ['demographic_static_pid',len(list(demographic_static_pid)),len(set.intersection(set(inpatient_pid) & set(demographic_static_pid)))],
            ['inpatient_specialty_pid',len(list(inpatient_specialty_pid)),len(set.intersection(set(inpatient_pid) & set(inpatient_specialty_pid)))],
            ['demographics_event_pid',len(list(demographics_event_pid)),len(set.intersection(set(inpatient_pid) & set(demographics_event_pid)))],
            ['outpatient_state_pid',len(list(outpatient_state_pid)),len(set.intersection(set(inpatient_pid) & set(outpatient_state_pid)))],
            ['measurements_bp_pid',len(list(measurements_bp_pid)),len(set.intersection(set(inpatient_pid) & set(measurements_bp_pid)))],
            ['lab_results_pid',len(list(lab_results_pid)),len(set.intersection(set(inpatient_pid) & set(lab_results_pid)))],
            ['measurements_pid',len(list(measurements_pid)),len(set.intersection(set(inpatient_pid) & set(measurements_pid)))]]
df_pid = pd.DataFrame(data_pid, columns = ['table name', 'number of unique pid','intersection pid'])
df_pid['percentage'] = df_pid['intersection pid'] / df_pid['number of unique pid'][0] 
df_pid

,table name,number of unique pid,intersection pid,percentage
0,inpatient_pid,16695,16695,1.000000
1,medications_pid,16431,12090,0.724169
2,immunization_pid,32784,15732,0.942318
3,procedures_pid,26894,12860,0.770291
4,demographic_static_pid,34768,16679,0.999042
5,inpatient_specialty_pid,22253,16022,0.959689
6,demographics_event_pid,34809,16693,0.999880
7,outpatient_state_pid,34809,16693,0.999880
8,measurements_bp_pid,16022,16022,0.959689
9,lab_results_pid,24370,11973,0.717161
10,measurements_pid,22255,16022,0.959689