In [1]:
import pandas as pd


import numpy as np
import pandas as pd

import seaborn as sns

import matplotlib.pyplot as plt
%matplotlib inline

from datetime import datetime

In [2]:
# no date
path = '/home/daisy/FDA_Dataset/demographics_static_quality_admission.csv'
demographic_static = pd.read_csv(path).iloc[:,1:]

# no date
path = '/home/daisy/FDA_Dataset/immunization_quality_admission.csv'
immunization = pd.read_csv(path).iloc[:,1:]

path = '/home/daisy/FDA_Dataset/inpatient_medications_ordered_cvd_mortality_quality.csv'
medications_ordered = pd.read_csv(path).iloc[:,1:]

path = '/home/daisy/FDA_Dataset/inpatient_procedures_clean_cvd_mortality_qaulity.csv'
procedures = pd.read_csv(path).iloc[:,1:]

path = '/home/daisy/FDA_Dataset/measurements_cvd_mortality_quality.csv'
measurements = pd.read_csv(path).iloc[:,1:]

In [3]:

# no date
path ='/home/vivi/FDA_datasets/inpatient_specialty_cvd_mortality_quality.csv'
inpatient_specialty = pd.read_csv(path).iloc[:,1:]

# no date
path ='/home/vivi/FDA_datasets/demographics_event_quality_admission.csv'
demographics_event = pd.read_csv(path).iloc[:,1:]
demographics_event = demographics_event.drop(columns = ['Age at update','State'])

# no date
path = '/home/vivi/FDA_datasets/outpatient_state_quality_admission.csv'
outpatient_state = pd.read_csv(path).iloc[:,1:]

path = '/home/vivi/FDA_datasets/inpatient_measurements_bp_cvd_mortality_quality.csv'
measurements_bp = pd.read_csv(path).iloc[:,1:]

In [4]:
path = '/home/hassan/lily/MLA/FDA/inpatient_cvd_mortality_quality.csv'
inpatient = pd.read_csv(path).iloc[:,1:]

path = '/home/hassan/lily/MLA/FDA/lab_results_features_quality.csv'
lab_results = pd.read_csv(path).iloc[:,1:]
lab_results = lab_results.rename(columns = {'count':'lab_count', 'freq':'lab_freq', 
                              'age_mean':'lab_age_mean', 'age_std':'lab_age_std'})

In [5]:
df1 = inpatient.merge(procedures, how = 'left', on = 'Internalpatientid')
df2 = df1.merge(demographic_static, how = 'left', on = 'Internalpatientid')
df3 = df2.merge(immunization, how = 'left', on = 'Internalpatientid')
df4 = df3.merge(medications_ordered, how = 'left', on = 'Internalpatientid')

df5 = df4.merge(inpatient_specialty, how = 'left', on = 'Internalpatientid')
df6 = df5.merge(demographics_event, how = 'left', on = 'Internalpatientid')
df7 = df6.merge(outpatient_state, how = 'left', on = 'Internalpatientid')
df8 = df7.merge(measurements_bp, how = 'left', on = 'Internalpatientid')

df9 = df8.merge(lab_results, how = 'left', on = 'Internalpatientid')
df = df9.merge(measurements, how = 'left', on = 'Internalpatientid')

In [6]:
df

,Internalpatientid,num_stays,stay_length,num_cvd_admission,CVD,Age 20-40,Age 40-60,Age 60-80,Age 80-100,Age 100-120,...,lab_count,lab_freq,lab_age_mean,lab_age_std,Height,Weight,Pulse oximetry min,Pulse oximetry max,Pulse oximetry mean,Pulse oximetry std
0,67,3,0.44,0,0,0,3,0,0,0,...,41.0,3.73,52.839098,2.984112,69.923239,188.761513,91.0,103.0,97.700000,3.097830
1,200,22,28.80,0,0,0,0,12,10,0,...,255.0,11.59,77.842169,5.340512,65.266667,176.164106,2.0,101.0,92.145161,9.032636
2,291,8,85.39,3,1,0,0,0,8,0,...,291.0,72.75,82.075826,1.268829,68.142857,163.106281,NaN,NaN,NaN,NaN
3,330,11,28.78,1,1,0,0,11,0,0,...,224.0,9.74,67.777557,5.561204,66.861628,279.201471,88.0,102.0,94.637363,3.507188
4,351,7,37.64,4,1,0,0,0,7,0,...,102.0,51.00,85.081594,0.454984,74.589345,240.791052,87.0,101.0,94.230769,2.898570
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
669,167102,23,16.18,0,0,0,0,21,2,0,...,398.0,19.90,70.900686,5.592250,75.970930,205.170035,91.0,102.0,96.535714,2.937398
670,167404,1,11.63,1,1,0,0,1,0,0,...,47.0,23.50,77.869365,0.274258,68.600000,135.054080,94.0,104.0,98.000000,3.505098
671,167907,1,0.01,0,0,0,0,0,1,0,...,10.0,0.91,81.460528,4.180655,NaN,NaN,NaN,NaN,NaN,NaN
672,167917,15,12.75,2,1,0,15,0,0,0,...,60.0,6.00,45.423213,2.501545,71.277778,223.816299,90.0,101.0,96.333333,2.777825
673,168008,19,29.21,0,0,0,0,19,0,0,...,167.0,33.40,71.735905,1.533223,68.850000,172.884283,81.0,105.0,98.813953,3.528136

In [7]:
df.columns

Index(['Internalpatientid', 'num_stays', 'stay_length', 'num_cvd_admission',
       'CVD', 'Age 20-40', 'Age 40-60', 'Age 60-80', 'Age 80-100',
       'Age 100-120', 'age_mean', 'age_std', 'age_min', 'age_max', 'stay_min',
       'stay_max', 'stay_mean', 'stay_std', 'freq', 'died_by_cvd',
       'num_unique_units', 'num_transfers', 'unique_admitting_specialty',
       'unique_discharging_specialty', 'DOMICILIARY', 'MEDICINE', 'NHCU',
       'NON-COUNT', 'OTHERS', 'PSYCHIATRY', 'SURGERY', 'Medical', 'Mental',
       'Others_Specialty', 'Rehab', 'Gerontology', 'total_procedure',
       'num_surgery_pro', 'Ethnicity', 'Gender', 'Races', 'Veteran flag',
       'Ethnicity_0', 'Ethnicity_1', 'Ethnicity_2', 'Races_0', 'Races_1',
       'Races_2', 'Races_3', 'num_immunization', 'Num med per admission mean',
       'Num med per admission min', 'Num med per admission max',
       'Total medications', 'mean age at specailty', 'period mean',
       'period std', 'specialty medical count', 'specialty support count',
       'specialty count', 'Event date', 'Marital status', 'Ruca category',
       'Marital status encoded', 'Ruca category encoded', 'State',
       'Age 20-40 hypotension', 'Age 40-60 hypotension',
       'Age 60-80 hypotension', 'Age 80-100 hypotension',
       'Age 100-120 hypotension', 'Age 20-40 healthy', 'Age 40-60 healthy',
       'Age 60-80 healthy', 'Age 80-100 healthy', 'Age 100-120 healthy',
       'Age 20-40 hypertension', 'Age 40-60 hypertension',
       'Age 60-80 hypertension', 'Age 80-100 hypertension',
       'Age 100-120 hypertension', 'lab_count', 'lab_freq', 'lab_age_mean',
       'lab_age_std', 'Height', 'Weight', 'Pulse oximetry min',
       'Pulse oximetry max', 'Pulse oximetry mean', 'Pulse oximetry std'],
      dtype='object')

In [8]:
df1_all = df.drop(columns = ['Event date','Marital status', 'Marital status encoded',
                        'State','Ruca category','Veteran flag'])
len(df1.columns)

38

In [9]:
df1_all.to_csv('/home/daisy/FDA_Dataset/final_cvd_mortality_quality_1.csv')

## Inner join

In [10]:
df1 = inpatient.merge(procedures, how = 'inner', on = 'Internalpatientid')
df2 = df1.merge(demographic_static, how = 'inner', on = 'Internalpatientid')
df3 = df2.merge(immunization, how = 'inner', on = 'Internalpatientid')
df4 = df3.merge(medications_ordered, how = 'inner', on = 'Internalpatientid')

df5 = df4.merge(inpatient_specialty, how = 'inner', on = 'Internalpatientid')
df6 = df5.merge(demographics_event, how = 'inner', on = 'Internalpatientid')
df7 = df6.merge(outpatient_state, how = 'inner', on = 'Internalpatientid')
df8 = df7.merge(measurements_bp, how = 'inner', on = 'Internalpatientid')

df9 = df8.merge(lab_results, how = 'inner', on = 'Internalpatientid')
df_2 = df9.merge(measurements, how = 'inner', on = 'Internalpatientid')

In [11]:
df_2_all = df_2.drop(columns = ['Event date','Marital status', 'Marital status encoded',
                        'State','Ruca category','Veteran flag'])

In [12]:
len(df_2_all.columns)

85

In [13]:
df_2_all.to_csv('/home/daisy/FDA_Dataset/final_cvd_mortality_quality_2.csv')

In [14]:
inpatient_pid = set(inpatient['Internalpatientid'])
medications_pid = set(medications_ordered['Internalpatientid'])
immunization_pid = set(immunization['Internalpatientid'])
procedures_pid = set(procedures['Internalpatientid'])
demographic_static_pid = set(demographic_static['Internalpatientid'])
inpatient_specialty_pid = set(inpatient_specialty['Internalpatientid'])
demographics_event_pid = set(demographics_event['Internalpatientid'])
outpatient_state_pid = set(outpatient_state['Internalpatientid'])
measurements_bp_pid =set(measurements_bp['Internalpatientid'])
lab_results_pid = set(lab_results['Internalpatientid'])
measurements_pid = set(measurements['Internalpatientid'])

In [16]:
data_pid = [['inpatient_pid',len(list(inpatient_pid)),len(set.intersection(set(inpatient_pid) & set(inpatient_pid)))],
            ['medications_pid',len(list(medications_pid)),len(set.intersection(set(inpatient_pid) & set(medications_pid)))],
            ['immunization_pid',len(list(immunization_pid)),len(set.intersection(set(inpatient_pid) & set(immunization_pid)))],
            ['procedures_pid',len(list(procedures_pid)),len(set.intersection(set(inpatient_pid) & set(procedures_pid)))],
            ['demographic_static_pid',len(list(demographic_static_pid)),len(set.intersection(set(inpatient_pid) & set(demographic_static_pid)))],
            ['inpatient_specialty_pid',len(list(inpatient_specialty_pid)),len(set.intersection(set(inpatient_pid) & set(inpatient_specialty_pid)))],
            ['demographics_event_pid',len(list(demographics_event_pid)),len(set.intersection(set(inpatient_pid) & set(demographics_event_pid)))],
            ['outpatient_state_pid',len(list(outpatient_state_pid)),len(set.intersection(set(inpatient_pid) & set(outpatient_state_pid)))],
            ['measurements_bp_pid',len(list(measurements_bp_pid)),len(set.intersection(set(inpatient_pid) & set(measurements_bp_pid)))],
            ['lab_results_pid',len(list(lab_results_pid)),len(set.intersection(set(inpatient_pid) & set(lab_results_pid)))],
            ['measurements_pid',len(list(measurements_pid)),len(set.intersection(set(inpatient_pid) & set(measurements_pid)))]]
df_pid = pd.DataFrame(data_pid, columns = ['table name', 'number of unique pid','intersection pid'])
df_pid['percentage'] = df_pid['intersection pid'] / df_pid['number of unique pid'][0] 
df_pid

,table name,number of unique pid,intersection pid,percentage
0,inpatient_pid,674,674,1.000000
1,medications_pid,452,452,0.670623
2,immunization_pid,939,644,0.955490
3,procedures_pid,1000,674,1.000000
4,demographic_static_pid,998,673,0.998516
5,inpatient_specialty_pid,632,632,0.937685
6,demographics_event_pid,632,632,0.937685
7,outpatient_state_pid,632,632,0.937685
8,measurements_bp_pid,632,632,0.937685
9,lab_results_pid,983,673,0.998516
10,measurements_pid,632,632,0.937685