**features**:

num_visits: total number of visits

stay_length: total length of unit stays (use service mean stay length to impute)

num_cvd_diagnosis: number of readmissions that are caused by cardiovascular

CVD: whether the patient has a cardiovescular diagnosis

*Different Age bins*: number of unit stays within this age range

age_mean: the mean admission age for each patient

age_std: the std of the admission age for each patient

AO: whether this patinet has been exposed to Agentorange

In [2]:
import pandas as pd

import numpy as np
import pandas as pd

import seaborn as sns
from importlib import reload
import matplotlib.pyplot as plt
import preprocess_data 

reload(preprocess_data)

%matplotlib inline

In [3]:
outpatient_visits = pd.read_csv('/home/bhatti/dataset/VCHAMPS/outpatient_visits_train.csv').iloc[:,1:]

In [4]:
outpatient_visits

,Internalpatientid,Age at visit,Visit start date,First listed diagnosis icd10 subcategory,Second listed diagnosis icd10 subcategory,Stop code,Agentorangeflag,Combatflag,Ionizingradiationflag,Serviceconnectedflag,Swasiaconditionsflag,State
0,1,60.619995,2004-11-17 14:35:36.0,Not specified,Not specified,TELEPHONE/MEDICINE,NaN,NaN,NaN,No,NaN,Indiana
1,1,61.032110,2005-04-17 05:40:07.0,Not specified,Not specified,TELEPHONE TRIAGE,NaN,NaN,NaN,Yes,NaN,Indiana
2,1,61.907075,2006-03-03 00:51:52.0,Not specified,Not specified,LABORATORY,NaN,NaN,NaN,NaN,NaN,Indiana
3,1,62.296573,2006-07-23 09:32:16.0,Not specified,Not specified,NO-COUNT,NaN,NaN,NaN,NaN,NaN,Indiana
4,1,63.632066,2007-11-23 12:28:48.0,Not specified,Not specified,GENERAL INTERNAL MEDICINE,NaN,NaN,NaN,No,NaN,Indiana
...,...,...,...,...,...,...,...,...,...,...,...,...
82692715,99999,96.300251,2013-03-19 17:47:55.0,Not specified,Not specified,TELEPHONE/ANCILLARY,NaN,NaN,NaN,No,NaN,Arizona
82692716,99999,96.322523,2013-03-27 21:10:33.0,Not specified,Not specified,NEUROLOGY,NaN,NaN,NaN,No,NaN,Arizona
82692717,99999,96.327503,2013-03-29 16:51:35.0,Not specified,Not specified,RENAL/NEPHROL(EXCEPT DIALYSIS),NaN,NaN,NaN,Yes,NaN,Arizona
82692718,99999,96.360092,2013-04-10 14:43:53.0,Not specified,Not specified,SPEECH-LANGUAGE PATHOLOGY,NaN,NaN,NaN,NaN,NaN,Arizona
82692719,99999,96.626156,2013-07-16 20:38:29.0,Not specified,Not specified,Not specified (no value),NaN,NaN,NaN,NaN,NaN,Arizona

### Drop Combatflag, Ionizingradiationflag, Serviceconnectedflag, Swasiaconditionsflag

In [5]:
outpatient_visits_drop = outpatient_visits.drop([ 'Combatflag', 'Ionizingradiationflag', 'Serviceconnectedflag', 'Swasiaconditionsflag'], axis=1)

In [6]:
outpatient_visits_drop

,Internalpatientid,Age at visit,Visit start date,First listed diagnosis icd10 subcategory,Second listed diagnosis icd10 subcategory,Stop code,Agentorangeflag,State
0,1,60.619995,2004-11-17 14:35:36.0,Not specified,Not specified,TELEPHONE/MEDICINE,NaN,Indiana
1,1,61.032110,2005-04-17 05:40:07.0,Not specified,Not specified,TELEPHONE TRIAGE,NaN,Indiana
2,1,61.907075,2006-03-03 00:51:52.0,Not specified,Not specified,LABORATORY,NaN,Indiana
3,1,62.296573,2006-07-23 09:32:16.0,Not specified,Not specified,NO-COUNT,NaN,Indiana
4,1,63.632066,2007-11-23 12:28:48.0,Not specified,Not specified,GENERAL INTERNAL MEDICINE,NaN,Indiana
...,...,...,...,...,...,...,...,...
82692715,99999,96.300251,2013-03-19 17:47:55.0,Not specified,Not specified,TELEPHONE/ANCILLARY,NaN,Arizona
82692716,99999,96.322523,2013-03-27 21:10:33.0,Not specified,Not specified,NEUROLOGY,NaN,Arizona
82692717,99999,96.327503,2013-03-29 16:51:35.0,Not specified,Not specified,RENAL/NEPHROL(EXCEPT DIALYSIS),NaN,Arizona
82692718,99999,96.360092,2013-04-10 14:43:53.0,Not specified,Not specified,SPEECH-LANGUAGE PATHOLOGY,NaN,Arizona
82692719,99999,96.626156,2013-07-16 20:38:29.0,Not specified,Not specified,Not specified (no value),NaN,Arizona

### Preprocess date

In [8]:
outpatient_visits_drop['Visit start date'] = outpatient_visits_drop['Visit start date'].apply(preprocess_data.preprocess_time_string)

In [9]:
outpatient_visits_drop

,Internalpatientid,Age at visit,Visit start date,First listed diagnosis icd10 subcategory,Second listed diagnosis icd10 subcategory,Stop code,Agentorangeflag,State
0,1,60.619995,2004-11-17 14:35:36,Not specified,Not specified,TELEPHONE/MEDICINE,NaN,Indiana
1,1,61.032110,2005-04-17 05:40:07,Not specified,Not specified,TELEPHONE TRIAGE,NaN,Indiana
2,1,61.907075,2006-03-03 00:51:52,Not specified,Not specified,LABORATORY,NaN,Indiana
3,1,62.296573,2006-07-23 09:32:16,Not specified,Not specified,NO-COUNT,NaN,Indiana
4,1,63.632066,2007-11-23 12:28:48,Not specified,Not specified,GENERAL INTERNAL MEDICINE,NaN,Indiana
...,...,...,...,...,...,...,...,...
82692715,99999,96.300251,2013-03-19 17:47:55,Not specified,Not specified,TELEPHONE/ANCILLARY,NaN,Arizona
82692716,99999,96.322523,2013-03-27 21:10:33,Not specified,Not specified,NEUROLOGY,NaN,Arizona
82692717,99999,96.327503,2013-03-29 16:51:35,Not specified,Not specified,RENAL/NEPHROL(EXCEPT DIALYSIS),NaN,Arizona
82692718,99999,96.360092,2013-04-10 14:43:53,Not specified,Not specified,SPEECH-LANGUAGE PATHOLOGY,NaN,Arizona
82692719,99999,96.626156,2013-07-16 20:38:29,Not specified,Not specified,Not specified (no value),NaN,Arizona

### Age at visit

Divide to different age bins: (20-40], (40-60], (60-80], (80-100], (100-120]

In [7]:
print(outpatient_visits_drop["Age at visit"].min())
print(outpatient_visits_drop["Age at visit"].max())

11.021683798196282
113.61559909687392

In [8]:
outpatient_visits_drop['Age 00-20'] = [0] * len(outpatient_visits_drop)
outpatient_visits_drop['Age 20-40'] = [0] * len(outpatient_visits_drop)
outpatient_visits_drop['Age 40-60'] = [0] * len(outpatient_visits_drop)
outpatient_visits_drop['Age 60-80'] = [0] * len(outpatient_visits_drop)
outpatient_visits_drop['Age 80-100'] = [0] * len(outpatient_visits_drop)
outpatient_visits_drop['Age 100-120'] = [0] * len(outpatient_visits_drop)
def age_category(data):
    data.loc[(data['Age at visit'] <= 20), 'Age 00-20'] = 1
    data.loc[(data['Age at visit'] > 20) & (data['Age at visit'] <= 40), 'Age 20-40'] = 1
    data.loc[(data['Age at visit'] > 40) & (data['Age at visit'] <= 60), 'Age 40-60'] = 1
    data.loc[(data['Age at visit'] > 60) & (data['Age at visit'] <= 80), 'Age 60-80'] = 1
    data.loc[(data['Age at visit'] > 80) & (data['Age at visit'] <= 100), 'Age 80-100'] = 1
    data.loc[(data['Age at visit'] > 100) & (data['Age at visit'] <= 120), 'Age 100-120'] = 1
    return data
outpatient_visits_drop = age_category(outpatient_visits_drop)
outpatient_visits_drop

,Internalpatientid,Age at visit,Visit start date,First listed diagnosis icd10 subcategory,Second listed diagnosis icd10 subcategory,Stop code,Agentorangeflag,State,Age 00-20,Age 20-40,Age 40-60,Age 60-80,Age 80-100,Age 100-120
0,1,60.619995,2004-11-17 14:35:36.0,Not specified,Not specified,TELEPHONE/MEDICINE,NaN,Indiana,0,0,0,1,0,0
1,1,61.032110,2005-04-17 05:40:07.0,Not specified,Not specified,TELEPHONE TRIAGE,NaN,Indiana,0,0,0,1,0,0
2,1,61.907075,2006-03-03 00:51:52.0,Not specified,Not specified,LABORATORY,NaN,Indiana,0,0,0,1,0,0
3,1,62.296573,2006-07-23 09:32:16.0,Not specified,Not specified,NO-COUNT,NaN,Indiana,0,0,0,1,0,0
4,1,63.632066,2007-11-23 12:28:48.0,Not specified,Not specified,GENERAL INTERNAL MEDICINE,NaN,Indiana,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82692715,99999,96.300251,2013-03-19 17:47:55.0,Not specified,Not specified,TELEPHONE/ANCILLARY,NaN,Arizona,0,0,0,0,1,0
82692716,99999,96.322523,2013-03-27 21:10:33.0,Not specified,Not specified,NEUROLOGY,NaN,Arizona,0,0,0,0,1,0
82692717,99999,96.327503,2013-03-29 16:51:35.0,Not specified,Not specified,RENAL/NEPHROL(EXCEPT DIALYSIS),NaN,Arizona,0,0,0,0,1,0
82692718,99999,96.360092,2013-04-10 14:43:53.0,Not specified,Not specified,SPEECH-LANGUAGE PATHOLOGY,NaN,Arizona,0,0,0,0,1,0
82692719,99999,96.626156,2013-07-16 20:38:29.0,Not specified,Not specified,Not specified (no value),NaN,Arizona,0,0,0,0,1,0

### Cardiovascular

In [12]:
cardiovascular = ["Heart failure, unspecified", "Other heart failure",
                  "Cardiogenic shock", "Hypertensive heart disease with heart failure",
                  "Hypertensive heart and kidney disease with heart failure", "Unstable angina", "Other forms of chronic ischemic heart disease",
                  "Atherosclerotic heart disease of native coronary artery", "Atrial fibrillation", "Atrial flutter",
                  "Supraventricular tachycardia", "Ventricular tachycardia"]

In [13]:
outpatient_visits_drop["cd_diagnosis"] = [0] * len(outpatient_visits_drop)
def cd_diagnosis(data):
    data.loc[(data["Second listed diagnosis icd10 subcategory"].str.contains('|'.join(cardiovascular))
      | data["Second listed diagnosis icd10 subcategory"].str.contains("Systolic (congestive) heart failure", regex=False)
      | data["Second listed diagnosis icd10 subcategory"].str.contains("Diastolic (congestive) heart failure", regex=False)
      | data["Second listed diagnosis icd10 subcategory"].str.contains("Combined systolic (congestive) and diastolic (congestive) heart failure", regex=False)
      | data["Second listed diagnosis icd10 subcategory"].str.contains("ST elevation (STEMI) myocardial infarction", regex=False)
      | data["Second listed diagnosis icd10 subcategory"].str.contains("Non-ST elevation (NSTEMI) myocardial infarction", regex=False)
      | data["First listed diagnosis icd10 subcategory"].str.contains('|'.join(cardiovascular))
      | data["First listed diagnosis icd10 subcategory"].str.contains("Systolic (congestive) heart failure", regex=False)
      | data["First listed diagnosis icd10 subcategory"].str.contains("Diastolic (congestive) heart failure", regex=False)
      | data["First listed diagnosis icd10 subcategory"].str.contains("Combined systolic (congestive) and diastolic (congestive) heart failure", regex=False)
      | data["First listed diagnosis icd10 subcategory"].str.contains("ST elevation (STEMI) myocardial infarction", regex=False)
      | data["First listed diagnosis icd10 subcategory"].str.contains("Non-ST elevation (NSTEMI) myocardial infarction", regex=False)), "cd_diagnosis"] = 1
    return data
outpatient_visits_drop = cd_diagnosis(outpatient_visits_drop)
outpatient_visits_drop

,Internalpatientid,Age at visit,Visit start date,First listed diagnosis icd10 subcategory,Second listed diagnosis icd10 subcategory,Stop code,Agentorangeflag,State,Age 00-20,Age 20-40,Age 40-60,Age 60-80,Age 80-100,Age 100-120,cd_diagnosis
0,1,60.619995,2004-11-17 14:35:36,Not specified,Not specified,TELEPHONE/MEDICINE,NaN,Indiana,0,0,0,1,0,0,0
1,1,61.032110,2005-04-17 05:40:07,Not specified,Not specified,TELEPHONE TRIAGE,NaN,Indiana,0,0,0,1,0,0,0
2,1,61.907075,2006-03-03 00:51:52,Not specified,Not specified,LABORATORY,NaN,Indiana,0,0,0,1,0,0,0
3,1,62.296573,2006-07-23 09:32:16,Not specified,Not specified,NO-COUNT,NaN,Indiana,0,0,0,1,0,0,0
4,1,63.632066,2007-11-23 12:28:48,Not specified,Not specified,GENERAL INTERNAL MEDICINE,NaN,Indiana,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82692715,99999,96.300251,2013-03-19 17:47:55,Not specified,Not specified,TELEPHONE/ANCILLARY,NaN,Arizona,0,0,0,0,1,0,0
82692716,99999,96.322523,2013-03-27 21:10:33,Not specified,Not specified,NEUROLOGY,NaN,Arizona,0,0,0,0,1,0,0
82692717,99999,96.327503,2013-03-29 16:51:35,Not specified,Not specified,RENAL/NEPHROL(EXCEPT DIALYSIS),NaN,Arizona,0,0,0,0,1,0,0
82692718,99999,96.360092,2013-04-10 14:43:53,Not specified,Not specified,SPEECH-LANGUAGE PATHOLOGY,NaN,Arizona,0,0,0,0,1,0,0
82692719,99999,96.626156,2013-07-16 20:38:29,Not specified,Not specified,Not specified (no value),NaN,Arizona,0,0,0,0,1,0,0

In [14]:
outpatient_visits_drop.columns

Index(['Internalpatientid', 'Age at visit', 'Visit start date',
       'First listed diagnosis icd10 subcategory',
       'Second listed diagnosis icd10 subcategory', 'Stop code',
       'Agentorangeflag', 'State', 'Age 00-20', 'Age 20-40', 'Age 40-60',
       'Age 60-80', 'Age 80-100', 'Age 100-120', 'cd_diagnosis'],
      dtype='object')

### Agentorange Imputation

In [15]:
len(outpatient_visits_drop[outpatient_visits_drop["Agentorangeflag"].isna()])/len(outpatient_visits_drop)

0.9631044183816907

In [127]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import log_loss
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.utils import resample

no_na = outpatient_visits_drop[outpatient_visits_drop['Agentorangeflag'].notna()]
only_na = outpatient_visits_drop[outpatient_visits_drop['Agentorangeflag'].isna()]

zero=no_na[no_na.Agentorangeflag==0]
one=no_na[no_na.Agentorangeflag==1]

#upsample minority
Agentorange_upsampled = resample(one,
                          replace=True, # sample with replacement
                          n_samples=len(zero), # match number in majority class
                          random_state=27) # reproducible results
# combine majority and upsampled minority
upsampled = pd.concat([zero, Agentorange_upsampled])

# use upsampled data to train the model
X = upsampled[['Age at visit', 'Transfer', 'stay_length', 'cd_diagnosis','DOMICILIARY', 'MEDICINE', 'NHCU', 'NON-COUNT',
       'OTHERS', 'PSYCHIATRY', 'SURGERY']].values
Y = upsampled['Agentorangeflag'].values


X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1, random_state=0)

forest = RandomFocrestClassifier(n_estimators=45, max_depth=25, random_state=False, 
                                max_features=0.6, min_samples_leaf=3, n_jobs=-1)

forest.fit(X_train, Y_train)

y_pred_train = forest.predict(X_train)
y_pred = forest.predict(X_test)

y_pred_proba = forest.predict_proba(X_test)

accuracy_train = accuracy_score(Y_train, y_pred_train)
accuracy_test = accuracy_score(Y_test, y_pred)

print("ACCURACY: TRAIN=%.4f TEST=%.4f" % (accuracy_train,accuracy_test))
print("LOG LOSS: "+str(log_loss(Y_test, y_pred_proba)))

ACCURACY: TRAIN=0.8662 TEST=0.8365
LOG LOSS: 0.39376561913846897

In [128]:
only_na = only_na[['Age at visit', 'Transfer', 'stay_length', 'cd_diagnosis','DOMICILIARY', 'MEDICINE', 'NHCU', 'NON-COUNT',
       'OTHERS', 'PSYCHIATRY', 'SURGERY']]
prediction = forest.predict(only_na)
only_na = outpatient_visits_drop[outpatient_visits_drop['Agentorangeflag'].isna()].drop('Agentorangeflag', axis=1)
only_na['Agentorangeflag'] = prediction

outpatient_visits_drop = [only_na, no_na]
outpatient_visits_drop = pd.concat(outpatient_visits_drop)

/home/hassan/.conda/envs/mla/lib/python3.10/site-packages/sklearn/base.py:432: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

### Final dataset

In [149]:
tidy_dataset = []
for ids, group in tqdm(outpatient_visits_drop.groupby("Internalpatientid")):

    readmission = 0
    num_admissions = group["Age at visit"].nunique()
    if num_admissions > 1: readmission=1

    age_mean = group["Age at visit"].mean()
    age_std = group["Age at visit"].std()
    if group["Age at visit"].nunique() == 1: age_std = 0

    min_age = group["Age at visit"].min()
    max_age = group["Age at visit"].max()
    freq = len(group)/(math.floor(max_age - min_age) + 1)

    num_cvd_readmission = max(0, group['cd_diagnosis'].sum() - 1)

    cvd = 0
    if group["cd_diagnosis"].sum() > 0: cvd = 1
    
    Died = 0
    if group["Died during admission"].sum() > 0: Died = 1

    AO = 0
    if group["Agentorangeflag"].sum() > 0: AO = 1

    df = pd.DataFrame(data={'Internalpatientid': [ids], 'num_stays': [len(group)], 'stay_length': group["stay_length"].sum(),
                            'num_unique_units': group["Admitting unit service"].nunique(), "num_transfers": group["Transfer"].sum(), 
                            "num_cvd_readmission": [num_cvd_readmission], "Readmission":[readmission], "Died": [Died], "AO": [AO], "CVD": [cvd],
                            "unique_admitting_specialty": group["Admitting specialty"].nunique(), "unique_discharging_specialty": group["Discharging specialty"].nunique(),
                            "DOMICILIARY": group["DOMICILIARY"].sum(), "MEDICINE": group["MEDICINE"].sum(), "NHCU":group["NHCU"].sum(),
                            "NON-COUNT":group["NON-COUNT"].sum(), "OTHERS":group["OTHERS"].sum(), 'PSYCHIATRY': group['PSYCHIATRY'].sum(), 'SURGERY': group['SURGERY'].sum(),
                            'Age 20-40': group["Age 20-40"].sum(), 'Age 40-60': group["Age 40-60"].sum(), 'Age 60-80':group["Age 60-80"].sum(), 
                            'Age 80-100':group["Age 80-100"].sum(), 'Age 100-120':group["Age 100-120"].sum(), "age_mean": [age_mean], "age_std": [age_std], "freq": [round(freq,2)]
                            })
    
    df = df.reset_index(drop=True)
    tidy_dataset.append(df)
    
tidy_dataset = pd.concat(tidy_dataset)

  0%|          | 0/84536 [00:00<?, ?it/s]

In [150]:
tidy_dataset.columns

Index(['Internalpatientid', 'num_stays', 'stay_length', 'num_unique_units',
       'num_transfers', 'num_cvd_readmission', 'Readmission', 'Died', 'AO',
       'CVD', 'unique_admitting_specialty', 'unique_discharging_specialty',
       'DOMICILIARY', 'MEDICINE', 'NHCU', 'NON-COUNT', 'OTHERS', 'PSYCHIATRY',
       'SURGERY', 'Age 20-40', 'Age 40-60', 'Age 60-80', 'Age 80-100',
       'Age 100-120', 'age_mean', 'age_std', 'freq'],
      dtype='object')

In [146]:
tidy_dataset.to_csv("inpatient_full.csv")